version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: docker/db/Dockerfile.migrate
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgresql:5432/customer
    depends_on:
      - postgresql

  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nestjs
  #   container_name: nestjs
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   # environment:
  #     # NODE_ENV: development # Set environment variable for Node.js environment (optional)
  #   volumes:
  #     - .:/app # Mount the current directory as a volume in the container

volumes:
  pgdata:
